#! /bin/bash

# NOTE: Chezmoi apply checker checks against last_modified date of file, not the content itself
cat << EOF > .config/chezmoi_last-apply.txt
PLEASE DO NOT EDIT THIS FILE MANUALLY

LAST MODIFIED:  $(date)
EOF