#!/bin/bash

BREWFILE=$CHEZMOI_SOURCE_DIR/private_readonly_dot_Brewfile
KREWFILE=$CHEZMOI_SOURCE_DIR/dot_config/private_readonly_kubectl-plugins.txt

echo "Writing Brew dumpfile (brews, casks, taps; no vscode plugins): $BREWFILE"
brew bundle dump --brews --casks --taps --force --file=$BREWFILE

echo "Writing Krew file: $KREWFILE"
kubectl-krew list > $KREWFILE

echo "Don't forget to run 'chezmoi apply' to sync the files..."
