#!/bin/bash

CHEZMOI_SOURCE=$(chezmoi source-path)
BREWFILE=$CHEZMOI_SOURCE/.Brewfile
KREWFILE=$CHEZMOI_SOURCE/dot_config/krew-plugins

echo "Writing Brew dumpfile: $BREWFILE"
brew bundle dump --force --file=$BREWFILE

echo "Writing Krew file: $KREWFILE"
kubectl-krew list > $KREWFILE

echo "Don't forget to run 'chezmoi apply' to sync the files..."
