#!/bin/bash

CHEZMOI_SOURCE=$(chezmoi source-path)
BREWFILE=$CHEZMOI_SOURCE/private_readonly_dot_Brewfile
KREWFILE=$CHEZMOI_SOURCE/dot_config/krew-plugins

echo "Writing Brew dumpfile (brews, casks, taps; no vscode plugins): $BREWFILE"
brew bundle dump --brews --casks --taps --force --file=$BREWFILE

echo "Writing Krew file: $KREWFILE"
kubectl-krew list > $KREWFILE

echo "Don't forget to run 'chezmoi apply' to sync the files..."
