right_format = """$kubernetes"""

[aws]
disabled = true

[golang]
symbol = 'GO '

[kubernetes]
disabled = false
format = '[$symbol ($user@)$cluster]($style) ctx [$context( \($namespace\))]($style)'
style = 'cyan'