"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
scan_timeout = 10
command_timeout = 500

right_format = """$kubernetes"""

[aws]
disabled = true

[gcloud]
disabled = true

[golang]
symbol = 'GO '

[kubernetes]
disabled = false
format = '[$symbol $context( \($namespace\))]($style)'
style = 'cyan'