right_format = """$kubernetes"""

[aws]
disabled = true

[gcloud]
disabled = true

[golang]
symbol = 'GO '

[kubernetes]
disabled = false
format = '[$symbol $context( \($namespace\))]($style)'
style = 'cyan'